# Generated by Django 3.1.1 on 2020-09-29 20:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('type', models.CharField(choices=[('NONE', 'Aucun'), ('MISS', 'Mademoiselle'), ('MRS', 'Madame'), ('MR', 'Monsieur'), ('COMPANY', 'Société')], default='NONE', max_length=16, verbose_name='Type')),
                ('country', models.CharField(choices=[('NONE', 'Aucun'), ('OTHER', 'Autre'), ('FR', 'France'), ('LU', 'Luxembourg'), ('DE', 'Allemagne'), ('BE', 'Belgique')], default='FR', max_length=8, verbose_name='Pays')),
                ('status', models.CharField(choices=[('OK', 'Ok'), ('BLOCKED', 'Bloqué'), ('CONTENTIOUS', 'Contentieux'), ('RECOVERY', 'Recouvrement'), ('UNDESIRED', 'Non désiré')], default='OK', max_length=16, verbose_name='Statut')),
                ('first_name', models.CharField(max_length=64, verbose_name='Prénom')),
                ('last_name', models.CharField(max_length=64, verbose_name='Nom')),
                ('email', models.EmailField(blank=True, max_length=255, verbose_name='Email')),
                ('phone', models.CharField(blank=True, max_length=32, verbose_name='Téléphone')),
                ('address', models.CharField(blank=True, max_length=32, verbose_name='Adresse')),
                ('city', models.CharField(blank=True, max_length=32, verbose_name='Ville')),
                ('zip', models.CharField(blank=True, max_length=32, verbose_name='Code postal')),
                ('origin', models.CharField(choices=[('NONE', 'Aucun'), ('INTERNET', 'Internet'), ('CAMPS', 'CAMPS'), ('LIBERAL', 'Libéral'), ('PMI', 'PMI')], default='NONE', max_length=16, verbose_name='Origine')),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name='Date de naissance')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('type', models.CharField(choices=[('NONE', 'Aucun'), ('INITIAL', 'Consultation initiale'), ('RESTITUTION', 'Restitution'), ('BILAN', 'Bilan'), ('FOLLOW_UP', 'Suivi'), ('SYNTHESIS', 'Synthèse')], default='NONE', max_length=16)),
                ('status', models.CharField(choices=[('NONE', 'Aucun'), ('COMING', 'A venir'), ('CANCELED', 'Annulé'), ('FINISHED', 'Terminé'), ('POSTPONED', 'Reporté')], default='NONE', max_length=16)),
                ('description', models.TextField(blank=True)),
                ('date', models.DateTimeField()),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='neuropsy.client')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
