# Generated by Django 3.1.1 on 2020-09-30 19:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('neuropsy', '0002_article'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='label',
            field=models.CharField(max_length=64, verbose_name='Label'),
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('NONE', 'Aucun'), ('CANCELED', 'Annulé'), ('FINISHED', 'Terminé'), ('POSTPONED', 'Reporté')], default='NONE', max_length=16)),
                ('description', models.TextField(blank=True)),
                ('date', models.DateTimeField()),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='neuropsy.client')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
