# Generated by Django 3.1.1 on 2020-10-01 06:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('neuropsy', '0003_auto_20200930_2153'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('description', models.TextField(blank=True)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='neuropsy.article')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='neuropsy.order')),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='articles',
            field=models.ManyToManyField(through='neuropsy.OrderData', to='neuropsy.Article'),
        ),
    ]
