# Generated by Django 3.1.1 on 2020-10-01 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('neuropsy', '0004_auto_20201001_0855'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='appointments',
            field=models.ManyToManyField(to='neuropsy.Appointment'),
        ),
    ]
