# Generated by Django 3.1.1 on 2020-10-01 07:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('neuropsy', '0005_order_appointments'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='appointments',
        ),
        migrations.AddField(
            model_name='appointment',
            name='order',
            field=models.ForeignKey(blank=True, default=0, on_delete=django.db.models.deletion.CASCADE, to='neuropsy.order'),
            preserve_default=False,
        ),
    ]
