# Generated by Django 3.1.1 on 2020-10-01 14:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('neuropsy', '0007_auto_20201001_1018'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('type', models.CharField(choices=[('NONE', 'Aucun'), ('CHECK', 'Chèque'), ('CASH', 'Espèce'), ('CREDIT_CARD', 'Carte de crédit'), ('TRANSFER', 'Virement'), ('OTHER', 'Autre')], default='NONE', max_length=16)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Montant')),
                ('date', models.DateTimeField()),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='neuropsy.client')),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='neuropsy.order')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
